char myChar;
char myChar2 = '\0';
char myChar3 = '\'';
char myChar4 = '\"';
char myChar5 = '\\';
char myChar6 = '\a';
char myChar7 = '\b';
char myChar8 = '\f';
char myChar9 = '\n';
char myChar10 = '\r';
char myChar11 = '\t';
char myChar12 = '\v';
char myChar13 = 'a';
char myChar14 = '3';